using System.Text;

namespace McpGuardrails.Core.Packs;

/// <summary>Writes one policy file out of several packs.</summary>
/// <remarks>
/// Generate, don't include. A runtime <c>include:</c> would hide rule order
/// across files, and in a first-match-wins policy order is the meaning; it
/// would also let an updated pack change behaviour on the next restart with no
/// file in the user's repository changing. A generated file keeps every rule
/// visible in one place, and a newer pack arrives only when the user re-runs
/// <c>init</c> and reviews the diff.
///
/// The output is deterministic - no date, no machine name - so re-running
/// <c>init</c> with the same packs is a no-op and the diff shows only what a
/// pack changed.
/// </remarks>
public static class PolicyComposer
{
    /// <summary>Composes the policy text.</summary>
    /// <param name="assignments">Packs and their servers, written in this order.</param>
    /// <param name="unassigned">Configured servers no pack covers, named in the header.</param>
    /// <remarks>
    /// Not re-parsed here: every pack was checked to load on its own when it was
    /// parsed, and rules scoped to different servers cannot conflict.
    /// </remarks>
    /// <exception cref="PackException">There is nothing to compose.</exception>
    public static string Compose(IReadOnlyList<PackAssignment> assignments, IReadOnlyList<string> unassigned)
    {
        ArgumentNullException.ThrowIfNull(assignments);
        ArgumentNullException.ThrowIfNull(unassigned);

        if (assignments.Count == 0)
        {
            throw new PackException("There are no packs to write.");
        }

        var text = new StringBuilder();
        text.Append("# Generated by 'mcp-guardrails init' from these packs:\n");
        foreach (var assignment in assignments)
        {
            text.Append($"#   {assignment.Pack.Name} (version {assignment.Pack.Version}) for server '{assignment.Server}'\n");
        }

        text.Append("#\n");
        text.Append("# This file is yours now: edit it freely. Rules run top to bottom and the\n");
        text.Append("# first match wins. Each pack's rules only match its own server, so the\n");
        text.Append("# order of the packs does not matter. To pick up newer packs, run init again\n");
        text.Append("# and review the difference before replacing this file.\n");
        if (unassigned.Count > 0)
        {
            text.Append("#\n");
            text.Append($"# No pack covers: {string.Join(", ", unassigned)}. Calls to their tools match no\n");
            text.Append("# rule here and are allowed (and audited) unless you add rules for them.\n");
        }

        text.Append('\n');
        text.Append("rules:\n");

        foreach (var assignment in assignments)
        {
            text.Append($"  # --- pack {assignment.Pack.Name} {assignment.Pack.Version}, server '{assignment.Server}' ---\n");
            foreach (var line in assignment.Pack.Comment.Split('\n'))
            {
                text.Append("  ").Append(line).Append('\n');
            }

            text.Append('\n');

            foreach (var line in assignment.Pack.RenderRules(assignment.Server))
            {
                text.Append(line).Append('\n');
            }

            text.Append('\n');
        }

        text.Append("  # Calls no rule above matched are allowed and audited. To refuse them\n");
        text.Append("  # instead, uncomment this catch-all:\n");
        text.Append("  #\n");
        text.Append("  # - name: deny-everything-else\n");
        text.Append("  #   decision: deny\n");
        text.Append("  #   message: This tool is not enabled for the agent. Ask the user.\n");

        return text.ToString();
    }
}
